### ISSUE TITLE
Option to display 4 block tiles in the single row

### ISSUE THREAD

**Issue by piotrpog** [mediakreativ/craft-blocksmith#1]
I think current 2 blocks per row layout might be too clunky in some cases. My suggestion is to add option to display 4 tiles per row in the plugin settings.

**Comment by schindlerchristian** [comment]
Hi @piotrpog,

first off, thank you so much for your suggestion and for taking the time to provide feedback on Blocksmith! I absolutely love your idea of adding more flexibility to the layout, and it inspired me to explore several options to improve the Narrow and Wide views.

### My Proposed Solution:

1. **Narrow View**:
   - Always displays 2 blocks per row (currently just 1).  

2. **Wide View**:
   - Default: Displays 2 blocks per row (as it is now).
   - Optional: Users can enable a setting to display **3 blocks per row**. Alternatively, we could allow 4 blocks per row if there's a strong preference.

### Why this approach?
- I think this builds upon your idea in a way that keeps things simple while adding valuable customization options.  
- Based on my testing, 3 blocks per row in the Wide View feel like a natural improvement for many use cases, but I’d love to hear your thoughts on this.

Here are some screenshots illustrating these changes:

**Narrow View (always 2 blocks):**  
<img width="910" alt="Screenshot 2024-12-08 at 13 17 18" src="https://github.com/user-attachments/assets/03a497bb-c5a1-474c-be80-31ae3bb3911e">

**Wide View:**  
- **Default (2 blocks):**  
<img width="1474" alt="Screenshot 2024-12-08 at 13 14 45" src="https://github.com/user-attachments/assets/d69b3629-30f5-4dbe-af78-5961f79c5b8c">

- **Optional Setting (3 blocks):**  
<img width="1474" alt="Screenshot 2024-12-08 at 13 15 03" src="https://github.com/user-attachments/assets/be5d5a30-2335-4782-9953-ff4da56408f3">

- **Optional Setting (4 blocks):**
<img width="1627" alt="Screenshot 2024-12-08 at 13 24 44" src="https://github.com/user-attachments/assets/3e06a79c-e7f6-421c-abaf-abe73568181d">

### What do you think?
Would you prefer 3 or 4 blocks as the optional Wide View setting? I’d love to hear your thoughts and refine this further based on your feedback.

Thanks again for your feedback and for helping improve Blocksmith!

Best regards,

Christian
