### ISSUE TITLE
Add option tostill use select dropdown, just with search field and options automatically sorted alphabetically

### ISSUE THREAD

**Issue by piotrpog** [mediakreativ/craft-blocksmith#3]
If possible, there could be option to both ope selection modal or use "old" dropdown, but with search field added to it. Options being automatically sorted alphabetically would be also nice touch

**Comment by schindlerchristian** [comment]
Hi @piotrprog, thank you for your suggestion! I was considering adding up to 5 Favorites to the context menu as an enhancement. These Favorites could make commonly used blocks more accessible. Would this approach address your request, or do you have other ideas in mind? Looking forward to your feedback!
